### ISSUE TITLE
Problems with pre-release identifiers

### ISSUE THREAD

**Issue by coderanger** [renovatebot/pep440#250]
**Describe the bug**

It appears that this implementation doesn't fully like pre-release versions.

```
WARN: pep440: failed to calculate newValue
{
  "result": "~=0.1.dev748+g3349dad",
  "newVersion": "0.1.dev748+g3349dad",
  "currentValue": "~=0.1.dev0"
}
```

**Steps to reproduce**

```
> satisfies("0.1.dev748+g3349dad", "~=0.1.dev748+g3349dad")
false
> satisfies("0.1.dev748+g3349dad", "==0.1.dev748+g3349dad")
true
```

**Comment by viceice** [comment]
@zharinov Can you have a look at this?

**Comment by zharinov** [comment]
@coderanger Seems like your problem is in some another layer, not in this repo:

```
>>> from packaging.specifiers import SpecifierSet
>>> SpecifierSet("==0.1.dev748+g3349dad")
<SpecifierSet('==0.1.dev748+g3349dad')>
>>> SpecifierSet("~=0.1.dev748+g3349dad")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.10/site-packages/packaging/specifiers.py", line 711, in __init__
    parsed.add(Specifier(specifier))
  File "/opt/homebrew/lib/python3.10/site-packages/packaging/specifiers.py", line 245, in __init__
    raise InvalidSpecifier(f"Invalid specifier: '{spec}'")
packaging.specifiers.InvalidSpecifier: Invalid specifier: '~=0.1.dev748+g3349dad'
```
